default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fintros-frontend-assignment

test:
  <<: *default
  database: fintros-frontend-assignment

production:
  <<: *default
  database: fintros-frontend-assignment
  username: fintros-frontend-assignment
  password: <%= ENV['fintros-frontend-assignment'] %>
